-- ============================================
-- 테이블 생성 스크립트
-- ============================================

-- 샘플 테이블 (기존)
CREATE TABLE TB_SAMPLE (
    ID VARCHAR2(50) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    USE_YN CHAR(1) DEFAULT 'Y' NOT NULL,
    REG_USER VARCHAR2(50) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL
);

COMMENT ON TABLE TB_SAMPLE IS '샘플 테이블';
COMMENT ON COLUMN TB_SAMPLE.ID IS '아이디';
COMMENT ON COLUMN TB_SAMPLE.NAME IS '이름';
COMMENT ON COLUMN TB_SAMPLE.DESCRIPTION IS '설명';
COMMENT ON COLUMN TB_SAMPLE.USE_YN IS '사용여부 (Y/N)';
COMMENT ON COLUMN TB_SAMPLE.REG_USER IS '등록자';
COMMENT ON COLUMN TB_SAMPLE.REG_DATE IS '등록일시';


-- 직원 정보 테이블 (w2ui 샘플용)
CREATE TABLE TB_EMPLOYEE (
    EMP_NO VARCHAR2(20) PRIMARY KEY,
    EMP_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100),
    PHONE VARCHAR2(20),
    DEPT_CODE VARCHAR2(20),
    DEPT_NAME VARCHAR2(100),
    POSITION VARCHAR2(50),
    HIRE_DATE DATE,
    SALARY NUMBER(12,2),
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    REG_USER VARCHAR2(50) NOT NULL,
    REG_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPD_USER VARCHAR2(50),
    UPD_DATE DATE
);

COMMENT ON TABLE TB_EMPLOYEE IS '직원 정보 테이블';
COMMENT ON COLUMN TB_EMPLOYEE.EMP_NO IS '사번';
COMMENT ON COLUMN TB_EMPLOYEE.EMP_NAME IS '직원명';
COMMENT ON COLUMN TB_EMPLOYEE.EMAIL IS '이메일';
COMMENT ON COLUMN TB_EMPLOYEE.PHONE IS '전화번호';
COMMENT ON COLUMN TB_EMPLOYEE.DEPT_CODE IS '부서코드';
COMMENT ON COLUMN TB_EMPLOYEE.DEPT_NAME IS '부서명';
COMMENT ON COLUMN TB_EMPLOYEE.POSITION IS '직급';
COMMENT ON COLUMN TB_EMPLOYEE.HIRE_DATE IS '입사일';
COMMENT ON COLUMN TB_EMPLOYEE.SALARY IS '급여';
COMMENT ON COLUMN TB_EMPLOYEE.STATUS IS '상태 (ACTIVE/INACTIVE/RETIRED)';
COMMENT ON COLUMN TB_EMPLOYEE.REG_USER IS '등록자';
COMMENT ON COLUMN TB_EMPLOYEE.REG_DATE IS '등록일시';
COMMENT ON COLUMN TB_EMPLOYEE.UPD_USER IS '수정자';
COMMENT ON COLUMN TB_EMPLOYEE.UPD_DATE IS '수정일시';

-- 인덱스 생성
CREATE INDEX IDX_EMPLOYEE_DEPT ON TB_EMPLOYEE(DEPT_CODE);
CREATE INDEX IDX_EMPLOYEE_STATUS ON TB_EMPLOYEE(STATUS);
CREATE INDEX IDX_EMPLOYEE_NAME ON TB_EMPLOYEE(EMP_NAME);
