-- ============================================
-- 샘플 데이터 삽입 스크립트
-- ============================================

-- TB_SAMPLE 샘플 데이터
INSERT INTO TB_SAMPLE (ID, NAME, DESCRIPTION, USE_YN, REG_USER, REG_DATE)
VALUES ('SAMPLE001', '샘플1', '첫 번째 샘플 데이터입니다.', 'Y', 'admin', SYSDATE);

INSERT INTO TB_SAMPLE (ID, NAME, DESCRIPTION, USE_YN, REG_USER, REG_DATE)
VALUES ('SAMPLE002', '샘플2', '두 번째 샘플 데이터입니다.', 'Y', 'admin', SYSDATE);

INSERT INTO TB_SAMPLE (ID, NAME, DESCRIPTION, USE_YN, REG_USER, REG_DATE)
VALUES ('SAMPLE003', '샘플3', '세 번째 샘플 데이터입니다.', 'N', 'admin', SYSDATE);


-- TB_EMPLOYEE 샘플 데이터
INSERT INTO TB_EMPLOYEE (EMP_NO, EMP_NAME, EMAIL, PHONE, DEPT_CODE, DEPT_NAME, POSITION, HIRE_DATE, SALARY, STATUS, REG_USER, REG_DATE)
VALUES ('E001', '김철수', 'kim.cs@example.com', '010-1234-5678', 'D001', '개발팀', '부장', TO_DATE('2018-03-15', 'YYYY-MM-DD'), 8000000, 'ACTIVE', 'admin', SYSDATE);

INSERT INTO TB_EMPLOYEE (EMP_NO, EMP_NAME, EMAIL, PHONE, DEPT_CODE, DEPT_NAME, POSITION, HIRE_DATE, SALARY, STATUS, REG_USER, REG_DATE)
VALUES ('E002', '이영희', 'lee.yh@example.com', '010-2345-6789', 'D001', '개발팀', '차장', TO_DATE('2019-06-01', 'YYYY-MM-DD'), 6500000, 'ACTIVE', 'admin', SYSDATE);

INSERT INTO TB_EMPLOYEE (EMP_NO, EMP_NAME, EMAIL, PHONE, DEPT_CODE, DEPT_NAME, POSITION, HIRE_DATE, SALARY, STATUS, REG_USER, REG_DATE)
VALUES ('E003', '박민수', 'park.ms@example.com', '010-3456-7890', 'D001', '개발팀', '과장', TO_DATE('2020-01-20', 'YYYY-MM-DD'), 5500000, 'ACTIVE', 'admin', SYSDATE);

INSERT INTO TB_EMPLOYEE (EMP_NO, EMP_NAME, EMAIL, PHONE, DEPT_CODE, DEPT_NAME, POSITION, HIRE_DATE, SALARY, STATUS, REG_USER, REG_DATE)
VALUES ('E004', '최지현', 'choi.jh@example.com', '010-4567-8901', 'D001', '개발팀', '대리', TO_DATE('2021-04-10', 'YYYY-MM-DD'), 4500000, 'ACTIVE', 'admin', SYSDATE);

INSERT INTO TB_EMPLOYEE (EMP_NO, EMP_NAME, EMAIL, PHONE, DEPT_CODE, DEPT_NAME, POSITION, HIRE_DATE, SALARY, STATUS, REG_USER, REG_DATE)
VALUES ('E005', '정수진', 'jung.sj@example.com', '010-5678-9012', 'D002', '기획팀', '부장', TO_DATE('2017-08-22', 'YYYY-MM-DD'), 8500000, 'ACTIVE', 'admin', SYSDATE);

INSERT INTO TB_EMPLOYEE (EMP_NO, EMP_NAME, EMAIL, PHONE, DEPT_CODE, DEPT_NAME, POSITION, HIRE_DATE, SALARY, STATUS, REG_USER, REG_DATE)
VALUES ('E006', '강민지', 'kang.mj@example.com', '010-6789-0123', 'D002', '기획팀', '차장', TO_DATE('2019-11-15', 'YYYY-MM-DD'), 7000000, 'ACTIVE', 'admin', SYSDATE);

INSERT INTO TB_EMPLOYEE (EMP_NO, EMP_NAME, EMAIL, PHONE, DEPT_CODE, DEPT_NAME, POSITION, HIRE_DATE, SALARY, STATUS, REG_USER, REG_DATE)
VALUES ('E007', '윤성호', 'yoon.sh@example.com', '010-7890-1234', 'D002', '기획팀', '과장', TO_DATE('2020-05-18', 'YYYY-MM-DD'), 5800000, 'ACTIVE', 'admin', SYSDATE);

INSERT INTO TB_EMPLOYEE (EMP_NO, EMP_NAME, EMAIL, PHONE, DEPT_CODE, DEPT_NAME, POSITION, HIRE_DATE, SALARY, STATUS, REG_USER, REG_DATE)
VALUES ('E008', '조은비', 'jo.eb@example.com', '010-8901-2345', 'D003', '영업팀', '차장', TO_DATE('2018-09-05', 'YYYY-MM-DD'), 6800000, 'ACTIVE', 'admin', SYSDATE);

INSERT INTO TB_EMPLOYEE (EMP_NO, EMP_NAME, EMAIL, PHONE, DEPT_CODE, DEPT_NAME, POSITION, HIRE_DATE, SALARY, STATUS, REG_USER, REG_DATE)
VALUES ('E009', '임재현', 'lim.jh@example.com', '010-9012-3456', 'D003', '영업팀', '과장', TO_DATE('2020-02-28', 'YYYY-MM-DD'), 5600000, 'ACTIVE', 'admin', SYSDATE);

INSERT INTO TB_EMPLOYEE (EMP_NO, EMP_NAME, EMAIL, PHONE, DEPT_CODE, DEPT_NAME, POSITION, HIRE_DATE, SALARY, STATUS, REG_USER, REG_DATE)
VALUES ('E010', '한서연', 'han.sy@example.com', '010-0123-4567', 'D003', '영업팀', '대리', TO_DATE('2021-07-12', 'YYYY-MM-DD'), 4800000, 'ACTIVE', 'admin', SYSDATE);

INSERT INTO TB_EMPLOYEE (EMP_NO, EMP_NAME, EMAIL, PHONE, DEPT_CODE, DEPT_NAME, POSITION, HIRE_DATE, SALARY, STATUS, REG_USER, REG_DATE)
VALUES ('E011', '송하늘', 'song.hn@example.com', '010-1111-2222', 'D004', '인사팀', '부장', TO_DATE('2016-05-10', 'YYYY-MM-DD'), 8200000, 'ACTIVE', 'admin', SYSDATE);

INSERT INTO TB_EMPLOYEE (EMP_NO, EMP_NAME, EMAIL, PHONE, DEPT_CODE, DEPT_NAME, POSITION, HIRE_DATE, SALARY, STATUS, REG_USER, REG_DATE)
VALUES ('E012', '백승현', 'baek.sh@example.com', '010-2222-3333', 'D004', '인사팀', '과장', TO_DATE('2020-10-01', 'YYYY-MM-DD'), 5700000, 'ACTIVE', 'admin', SYSDATE);

INSERT INTO TB_EMPLOYEE (EMP_NO, EMP_NAME, EMAIL, PHONE, DEPT_CODE, DEPT_NAME, POSITION, HIRE_DATE, SALARY, STATUS, REG_USER, REG_DATE)
VALUES ('E013', '남궁민', 'namgung.m@example.com', '010-3333-4444', 'D005', '재무팀', '차장', TO_DATE('2019-03-20', 'YYYY-MM-DD'), 6900000, 'ACTIVE', 'admin', SYSDATE);

INSERT INTO TB_EMPLOYEE (EMP_NO, EMP_NAME, EMAIL, PHONE, DEPT_CODE, DEPT_NAME, POSITION, HIRE_DATE, SALARY, STATUS, REG_USER, REG_DATE)
VALUES ('E014', '선우지훈', 'sunwoo.jh@example.com', '010-4444-5555', 'D005', '재무팀', '대리', TO_DATE('2021-11-08', 'YYYY-MM-DD'), 4700000, 'ACTIVE', 'admin', SYSDATE);

INSERT INTO TB_EMPLOYEE (EMP_NO, EMP_NAME, EMAIL, PHONE, DEPT_CODE, DEPT_NAME, POSITION, HIRE_DATE, SALARY, STATUS, REG_USER, REG_DATE)
VALUES ('E015', '황보미래', 'hwangbo.mr@example.com', '010-5555-6666', 'D001', '개발팀', '사원', TO_DATE('2022-03-02', 'YYYY-MM-DD'), 3800000, 'ACTIVE', 'admin', SYSDATE);

COMMIT;
