-- 부서 테이블
CREATE TABLE TB_DEPARTMENT (
    DEPT_CODE VARCHAR2(10) PRIMARY KEY,
    DEPT_NAME VARCHAR2(100) NOT NULL,
    DEPT_MANAGER VARCHAR2(50),
    LOCATION VARCHAR2(100),
    BUDGET NUMBER(15, 0),
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    REG_USER VARCHAR2(50),
    REG_DATE DATE DEFAULT SYSDATE,
    UPD_USER VARCHAR2(50),
    UPD_DATE DATE
);

-- 부서별 통계 테이블 (집계용)
CREATE TABLE TB_DEPT_STATISTICS (
    DEPT_CODE VARCHAR2(10) PRIMARY KEY,
    DEPT_NAME VARCHAR2(100),
    TOTAL_EMPLOYEES NUMBER(10, 0) DEFAULT 0,
    AVG_SALARY NUMBER(15, 2) DEFAULT 0,
    MAX_SALARY NUMBER(15, 0) DEFAULT 0,
    MIN_SALARY NUMBER(15, 0) DEFAULT 0,
    TOTAL_BUDGET NUMBER(15, 0) DEFAULT 0,
    YEAR NUMBER(4),
    MONTH NUMBER(2),
    REG_DATE DATE DEFAULT SYSDATE,
    UPD_DATE DATE,
    CONSTRAINT FK_DEPT_STATS FOREIGN KEY (DEPT_CODE) REFERENCES TB_DEPARTMENT(DEPT_CODE)
);

-- 부서 샘플 데이터
INSERT INTO TB_DEPARTMENT (DEPT_CODE, DEPT_NAME, DEPT_MANAGER, LOCATION, BUDGET, STATUS, REG_USER, REG_DATE)
VALUES ('D001', '개발팀', '김철수', '서울 본사 3층', 500000000, 'ACTIVE', 'admin', SYSDATE);

INSERT INTO TB_DEPARTMENT (DEPT_CODE, DEPT_NAME, DEPT_MANAGER, LOCATION, BUDGET, STATUS, REG_USER, REG_DATE)
VALUES ('D002', '기획팀', '정수진', '서울 본사 4층', 300000000, 'ACTIVE', 'admin', SYSDATE);

INSERT INTO TB_DEPARTMENT (DEPT_CODE, DEPT_NAME, DEPT_MANAGER, LOCATION, BUDGET, STATUS, REG_USER, REG_DATE)
VALUES ('D003', '영업팀', '조은비', '서울 본사 5층', 400000000, 'ACTIVE', 'admin', SYSDATE);

INSERT INTO TB_DEPARTMENT (DEPT_CODE, DEPT_NAME, DEPT_MANAGER, LOCATION, BUDGET, STATUS, REG_USER, REG_DATE)
VALUES ('D004', '인사팀', '박지훈', '서울 본사 2층', 200000000, 'ACTIVE', 'admin', SYSDATE);

INSERT INTO TB_DEPARTMENT (DEPT_CODE, DEPT_NAME, DEPT_MANAGER, LOCATION, BUDGET, STATUS, REG_USER, REG_DATE)
VALUES ('D005', '재무팀', '이소영', '서울 본사 6층', 250000000, 'ACTIVE', 'admin', SYSDATE);

-- 부서별 통계 샘플 데이터 (2026년 1월 기준)
INSERT INTO TB_DEPT_STATISTICS (DEPT_CODE, DEPT_NAME, TOTAL_EMPLOYEES, AVG_SALARY, MAX_SALARY, MIN_SALARY, TOTAL_BUDGET, YEAR, MONTH, REG_DATE)
SELECT
    e.DEPT_CODE,
    e.DEPT_NAME,
    COUNT(*) AS TOTAL_EMPLOYEES,
    ROUND(AVG(e.SALARY), 2) AS AVG_SALARY,
    MAX(e.SALARY) AS MAX_SALARY,
    MIN(e.SALARY) AS MIN_SALARY,
    d.BUDGET AS TOTAL_BUDGET,
    2026 AS YEAR,
    1 AS MONTH,
    SYSDATE AS REG_DATE
FROM TB_EMPLOYEE e
INNER JOIN TB_DEPARTMENT d ON e.DEPT_CODE = d.DEPT_CODE
GROUP BY e.DEPT_CODE, e.DEPT_NAME, d.BUDGET;

COMMIT;

-- 인덱스 생성
CREATE INDEX IDX_DEPT_NAME ON TB_DEPARTMENT(DEPT_NAME);
CREATE INDEX IDX_DEPT_STATUS ON TB_DEPARTMENT(STATUS);
CREATE INDEX IDX_DEPT_STATS_YEAR_MONTH ON TB_DEPT_STATISTICS(YEAR, MONTH);
